### ISSUE TITLE
bitset_minimum returns 0 for an empty set

### ISSUE THREAD

**Issue by cloudydev** [lemire/cbitset#13]
```
bitset_t * b1 = bitset_create();
bitset_set(b1,0);
assert(bitset_minimum(b) == 0);
bitset_t * b2 = bitset_create();
assert(bitset_minimum(b2) == 0);
```

**Comment by lemire** [comment]
<img width="613" alt="Capture d’écran, le 2023-06-14 à 09 43 35" src="https://github.com/lemire/cbitset/assets/391987/37b70399-3334-4d95-a8a3-ba0c5242fd2a">

Yes. This is explicitly documented as doing so. It is the correct behaviour.
