### ISSUE TITLE
Use of `restrict` for Compatibility with MSVC

### ISSUE THREAD

**Issue by RoyiAvital** [lemire/cbitset#8]
In the `h` file you use:

```
struct bitset_s {
    uint64_t * restrict array;
    size_t arraysize;
    size_t capacity;

};
```

The use of `restrict` isn't compatible with MSVC.
Maybe some Macro to be compatible with MSVC?

I can create a pull if you want.

By the way, let's say I want `numSets` bit sets (Run time parameter) of `numBits` (Run Time parameter) bits each.  
What would be the performance wise way to do it? Can I allocate one pointer with allocation of `numBits * numSets`? Or there is an issue with that?

**Comment by lemire** [comment]
> The use of restrict isn't compatible with MSVC.

Because Visual Studio does not support the C standard (C11).

> I can create a pull if you want. 

Please do.

> By the way, let's say I want numSets bit sets (Run time parameter) of numBits (Run Time parameter) bits each. What would be the performance wise way to do it? 

It is hard to discuss abstract questions such as that one without context.

**Comment by RoyiAvital** [comment]
I created a pull request: https://github.com/lemire/cbitset/pull/9.

By the way, it seems you use `malloc()` and then `memset()` to set to `0`.
Wouldn't it be better just to use `calloc()`? I can do a pull on that as well.

**Comment by lemire** [comment]
> By the way, it seems you use malloc() and then memset() to set to 0. Wouldn't it be better just to use calloc()? I can do a pull on that as well.

You mean in bitset_create_with_capacity?

**Comment by RoyiAvital** [comment]
Yes. I think that's the case I saw.

**Comment by lemire** [comment]
> Yes. I think that's the case I saw.

Then yes, sure, please do a PR.
